# TODO : 각자 개발용 URL, 개인 Database명 입력 필요, 해당 2개의 속성은 커밋 제외 필수!!!!!
hook:
  db:
    url: db-it7f7-kr.vpc-pub-cdb.ntruss.com
    database: sh
    username: hooklocal
    password: hooklocal1234!
    port: 3306
  mail:
    register-domain: localhost:3000


spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQLDialect

    hibernate:
      # 매번 create생성 시키기 위함
      ddl-auto: create-drop

    # DDL(CREATE TABLE) 등의 문구를 직접 보기 위한 설정
    generate-ddl: true
    # sql init mode를 활용시 해당 설정이 필요하다.
    defer-datasource-initialization: true
    open-in-view: off

  # resources/data.sql의 파일을 매번 입력한다.
  sql:
    init:
      mode: always

oauth2:
  kakao:
    base-url: https://kauth.kakao.com
    client-id: 2899d52a6041d90ae4c9b9645a7c291d
    client-secret: 9nI9kKWteLr6kMH50gXTs8HbJ5qvRVq4
    redirect-url: http://localhost:3000/auth/oauth/kakao
    app-id: d13220db279c497ef47b29323ceb2e20
    admin-key: 262a014744528270dde2033856929ddb

  google:
    base-url: https://accounts.google.com
    client-id: 591530286414-6ldlggvbn3o95m7aphh6d6cunq18jkge.apps.googleusercontent.com
    client-secret: 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
    redirect-uri: http://localhost:3000/auth/oauth/google
    scope:
      - email
      - profile
