spring:
  profiles:
    active: local
    include:
      - db
      - auth
      - papago


  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # 파일 한개 최대 20MB, 최대 Request 600MB로 20MB사진 30장까지 허용
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 600MB

naver:
  storage:
    end-point: https://kr.object.ncloudstorage.com
    region-name: kr-standard
    bucket-name: hook-killer-file-bucket

auth:
  jwt:
    header: "Authorization"
    prefix: "Bearer "
    secret-key: hokasdofkoasdkfoafjasdlkfjsadlkfjeijflasdkfjasdfasdfasdfaefargagstrghehasdfasfaegargasfsadfdaga
    access-exp: 36000
    refresh-exp: 3600
    issuer: hookkiller
    exclude-path: [
      "/api/**",
      "/user/**"
    ]

