name: CI

on:
  pull_request:
    branches: [ "dev", "feat" ]
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: Hook-Killer CI
    runs-on: ubuntu-latest

    steps:
      - name: Github Action Version Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build